export const sneakers = [
  {
    name: "Women's Green Training",
    price: "64.90",
    discountedPrice: "49.90",
    img: "images/Shoe for sale/Sneaker-1.jpg",
    category: "Women",
    altCategory: "Training",
  },
  {
    name: "Women's Pink Training",
    price: "64.90",
    discountedPrice: "54.90",
    img: "images/Shoe for sale/Sneaker-2.jpg",
    category: "Women",
    altCategory: "Training",
  },
  {
    name: "Women's Peach Training",
    price: "69.90",
    discountedPrice: "57.90",
    img: "images/Shoe for sale/Sneaker-14.jpg",
    category: "Women",
    altCategory: "Training",
  },
  {
    name: "Men's Red Running",
    price: "79.90",
    discountedPrice: "69.90",
    img: "images/Shoe for sale/Sneaker-16.jpg",
    category: "Men",
    altCategory: "Running",
  },
  {
    name: "Men's Black Running",
    price: "79.90",
    img: "images/Shoe for sale/Sneaker-15.jpg",
    category: "Men",
    altCategory: "Running",
  },
  {
    name: "Men's Navy Running",
    price: "104.90",
    img: "images/Shoe for sale/Sneaker-18.jpg",
    category: "Men",
    altCategory: "Running",
  },
  {
    name: "Women's Blue Training",
    price: "69.90",
    discountedPrice: "60.00",
    img: "images/Shoe for sale/Sneaker-13.jpg",
    category: "Women",
    altCategory: "Training",
  },
  {
    name: "Men's Green Running",
    price: "104.90",
    discountedPrice: "89.90",
    img: "images/Shoe for sale/Sneaker-17.jpg",
    category: "Men",
    altCategory: "Running",
  },
  {
    name: "Women's Tan Sneaker",
    price: "89.90",
    discountedPrice: "80.00",
    img: "images/Shoe for sale/Sneaker-3.jpg",
    category: "Women",
    altCategory: "Sneaker",
  },
  {
    name: "Women's Mint Sneaker",
    price: "89.90",
    img: "images/Shoe for sale/Sneaker-20.jpg",
    category: "Women",
    altCategory: "Sneaker",
  },
  {
    name: "Men's Earth-Tone Sneaker",
    price: "74.90",
    img: "images/Shoe for sale/Sneaker-9.jpg",
    category: "Men",
    altCategory: "Sneaker",
  },
  {
    name: "Men's Moonstone Sneaker",
    price: "74.90",
    img: "images/Shoe for sale/Sneaker-10.jpg",
    category: "Men",
    altCategory: "Sneaker",
  },
  {
    name: "Women's Candy City Run",
    price: "54.90",
    discountedPrice: "40.00",
    img: "images/Shoe for sale/Sneaker-6.jpg",
    category: "Women",
    altCategory: "Run",
  },
  {
    name: "Women's Tosca City Run",
    price: "64.00",
    img: "images/Shoe for sale/Sneaker-4.jpg",
    category: "Women",
    altCategory: "Run",
  },
  {
    name: "Women's Choco City Run",
    price: "64.00",
    img: "images/Shoe for sale/Sneaker-5.jpg",
    category: "Women",
    altCategory: "Run",
  },
  {
    name: "Men's Classic Blue",
    price: "79.90",
    img: "images/Shoe for sale/Sneaker-11.jpg",
    category: "Men",
    altCategory: "Classic",
  },
  {
    name: "Women's Pink Suede",
    price: "59.90",
    img: "images/Shoe for sale/Sneaker-8.jpg",
    category: "Women",
    altCategory: "Suede",
  },
  {
    name: "Women's Orange Sneaker",
    price: "44.90",
    img: "images/Shoe for sale/Sneaker-19.jpg",
    category: "Women",
    altCategory: "Sneaker",
  },
  {
    name: "Women's Cream Suede",
    price: "59.90",
    img: "images/Shoe for sale/Sneaker-7.jpg",
    category: "Women",
    altCategory: "Suede",
  },
  {
    name: "Men's Classic Mint",
    price: "79.90",
    discountedPrice: "69.00",
    img: "images/Shoe for sale/Sneaker-12.jpg",
    category: "Men",
    altCategory: "Classic",
  },
];
