export { default as Homepage } from "./Homepage/Homepage";
export { default as Layout } from "./Layout/Layout";
export { default as Men } from "./Men/Men";
export { default as Women } from "./Women/Women";
export { default as Collection } from "./Collection/Collection";
export { default as Lookbook } from "./Lookbook/Lookbook";
export { default as Sale } from "./Sale/Sale";
export { default as Story } from "./Story/Story";
export { default as Contact } from "./Contact/Contact";
